---
#slider puzzle config
config:
  #search algorithm to be used by the solver
  #possible options are:
  # - bfs
  # - dfs
  # - iddfs
  # - hls
  # - hgs
  # - a*
  algorithm: 'dfs'

  # depth limit for iddfs [ignored for other algorithms]
  # limit: '0'

  # heuristic to be used for informed search algorithms [ignored for other algorithms]
  #possible options are:
  # - manhattan
  # - humming
  # - overestimated
  # heuristic: ''

...