---
# --- Neural Network Config ---
config:

  # Input and Output file paths for the training values
  training_values:
    input: training_values/ej3-2-input.txt
    output: training_values/ej3-3-output.txt
    #    input: training_values/ej1-xor-input.txt
    #    output: training_values/ej1-xor-output.txt
  #    input:
  #    output:

  # Plot results
  plot: true

  #Perceptron config
  perceptron:
    #Perceptron type
    #Values:
    # - simple
    # - linear
    # - non_linear
    # - multilayer
    type: non_linear

    #Perceptron specific settings
    settings:
      #Global
      learning_rate: 0.01
      min_error: 0.01
      min_iter: 60000
      mutation_probability: 0.02

      #Non-Linear
      g: tanh
      b: 2
...