---
# --- Neural Network Config ---
config:

  # Input and Output file paths for the training values
  training_values:
    #    input: training_values/ej3-2-input.txt
    #    output: training_values/ej3-2-output.txt
    #    output: training_values/ej3-3-output.txt
    #    input: training_values/ej1-xor-input.txt
    #    output: training_values/ej1-xor-output.txt
    #    input: training_values/ej2-linear-input.txt
    #    output: training_values/ej2-linear-output.txt
    input:
    output:

  # Plot results
  plot: true

  #Perceptron config
  perceptron:
    #Perceptron type
    #Values:
    # - simple
    # - linear
    # - non_linear
    # - multilayer
    type: non_linear

    #Perceptron specific settings
    settings:
      #Global
      learning_rate: 0.1
      min_error: 0.0000005
      min_iter: 5000

      #Non-Linear
      g: logistic
      b: 0.1

      #Momentum and adaptive lr
      variable: false
      alpha: 0.6 #recomended 0.8 or 0.9
      a: 0.01
      beta: 0.1


...