---
#backpack problem config
config:

  #initial population size (n>5)
  initial_population: 10

  #end condition to be used by the solver
  end_condition:

    #defines how many generations should be generated before ending
    generations_count: 20000 #generations_count>=500, defaults to 500

    #defines how many generations should be generated at least before ending via acceptable solution
    acceptable_solution_generation_count: 10000 #acceptable_solution_generation_count>=500, defaults to 500

    #used for time type, defines how many seconds should pass before ending
    time: 'time' #time>0, defaults to 5*60

    #defines how many consecutive generations should be generated
    #with a percentage of equal individuals before ending
    structure:
      percentaje: 'percentage' #(0<p<1), defaults to 0.8
      generations: 'generations' #generations>=10, defaults to 10
      min_generations: 'min_generations' #min_generations>=500, defaults to 500

    #defines how many consecutive generations should be generated
    #with the same best fitness
    fitness:
      generations: 20 #generations>=10, defaults to 10
      min_generations: 10000 #min_generations>=500, defaults to 500

  #fitness function to be used by the solver
  #possible options are:
  # - benefit_weight_ratio
  # - no_overweight_fitness
  fitness_function: benefit_weight_ratio

  #couple selection method to be used by the solver
  #possible options are:
  # - rand_couple_selection
  # - fitness_couple_selection
  couple_selection: rand_couple_selection

  #crossover method to be used by the solver
  crossover:
    #possible types are:
    # - simple_crossover
    # - multiple_crossover
    # - uniform_crossover
    type: simple_crossover

    #used for truncated_selection type, defines how many chromosomes are discarded from the generation
    multiple_crossover:
      n: 10 # n>0

  #mutation probability used for mutating chromosomes (0<p<1)
  mutation_probability: 0.005

  #selection method to be used by the solver
  selection:

    #possible types are:
    # - elitism_selection
    # - roulette_wheel_selection
    # - rank_selection
    # - tournament_selection
    # - boltzmann_selection
    # - truncated_selection
    type: roulette_wheel_selection

    #used for truncated_selection type, defines how many chromosomes are discarded from the generation and the
    #sample size to extract on each iteration
    truncated_selection:
      truncation_size: 'truncation_size' # truncation_size>0

...