---
#backpack problem config
config:

  #initial population size (n>5)
  initial_population: 10

  #end condition to be used by the solver
  end_condition:

    #defines how many generations should be generated before ending
    generations_count: 50000 #generations_count>=500, defaults to 500

    #defines how many generations should be generated at least before ending via acceptable solution
    acceptable_solution_generation_count: 10000 #acceptable_solution_generation_count>=500, defaults to 500

    #used for time type, defines how many seconds should pass before ending
    time: 'time' #time>0, defaults to 5*60

    #defines how many consecutive generations should be generated
    #with a percentage of equal individuals before ending
    structure:
      percentaje: 0.7 #(0<p<1), defaults to 0.8
      generations: 10 #generations>=10, defaults to 10
      min_generations: 50000 #min_generations>=500, defaults to 500

    #defines how many consecutive generations should be generated
    #with the same best fitness
    fitness:
      generations: 15 #generations>=10, defaults to 10
      min_generations: 50000 #min_generations>=500, defaults to 500

  #fitness function to be used by the solver
  #possible options are:
  # - benefit_weight_ratio
  fitness_function: benefit_weight_ratio

  #couple selection method to be used by the solver
  #possible options are:
  # - rand_couple_selection
  # - fitness_couple_selection
  couple_selection: rand_couple_selection

  #crossover method to be used by the solver
  crossover:
    #possible types are:
    # - simple_crossover
    # - multiple_crossover
    # - uniform_crossover
    type: uniform_crossover

    #used for truncated_selection type, defines how many chromosomes are discarded from the generation
    multiple_crossover:
      n: 10 # 0<n<initial_population

  #mutation probability used for mutating chromosomes (0<p<1)
  mutation_probability: 0.05

  #selection method to be used by the solver
  selection:

    #possible types are:
    # - elitism_selection
    # - roulette_wheel_selection
    # - rank_selection
    # - tournament_selection
    # - boltzmann_selection
    # - truncated_selection
    type: truncated_selection

    #used for boltzmann_selection type, defines temperature function parameters
    boltzmann_selection:
      Tc: '10' # 0<Tc<T0
      T0: '300' # T0>Tc
      k: '0.5' # k>0

    #used for truncated_selection type, defines how many chromosomes are discarded from the generation
    truncated_selection:
      truncation_size: 5 # 0<truncation_size<=population_size

...