---
# --- Unsupervised Learning Config ---
config:

  # Input and Output file paths for the input values
  input_file:

  #Kohonen config
  kohonen:
    #network learning rate
    learning_rate: 0.01
    #network radius
    radius: 4
    #network max iterations
    max_iter: 1000
    #network k neurons
    k: 4

  #Hopfield config
  hopfield:
    #network max iterations
    max_iter: 100

  #Oja config
  oja:
    #network learning rate
    learning_rate: 0.0001
    #network max iterations
    max_iter: 10000
...