---
# --- Autoencoders Config ---
config:

  # Input and Output file paths for the input values
  # Values:
  # - 1 numbers
  # - 2 uppercase characters
  # - 3 lowercase characters
  font: 2

  # font values selection amount
  selection_amount: 5

  #network max iterations
  max_iter: 100
  #network min error
  min_error: 0.01
  #network latent layer
  latent_layer: 2
  #network intermediate layers
  intermediate_layers: [256]
...